/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.kamilereon.lylac_system;

import org.bukkit.Bukkit;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;
import net.kamilereon.lylac_system.command.LylacCommandListener;
import net.kamilereon.lylac_system.listener.EntityInteractListener;
import net.kamilereon.lylac_system.listener.PlayerListener;
import net.kyori.adventure.text.Component;

public class LylacSystem extends JavaPlugin implements Listener {
    private static LylacSystem lylacSystem;

    public static LylacSystem getLylacSystem() {
        return lylacSystem;
    }

    @Override
    public void onEnable() {
        lylacSystem = this;
        Bukkit.broadcast(Component.text("lylacsystem v0.0.1 enabled"));
        Bukkit.getPluginManager().registerEvents(new EntityInteractListener(), this);
        Bukkit.getPluginManager().registerEvents(new PlayerListener(), this);
        this.getCommand("lylac").setExecutor(new LylacCommandListener());
    }

    @Override
    public void onDisable() {
        LylacSystemRegistry.getPlayerWrappers().stream().forEach(p -> {
            p.fin();
        });
    }

    @Override
    public void onLoad() {
        Bukkit.getOnlinePlayers().forEach(p -> {
            LylacSystemRegistry.getOrCreatePlayerWrapper(p);
        });
    }
}
