/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    id("com.github.johnrengelman.shadow") version("8.1.1")
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://repo.dmulloy2.net/repository/public/")
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:32.1.1-jre")
    compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT")

    compileOnly("org.projectlombok:lombok:1.18.30")
	annotationProcessor("org.projectlombok:lombok:1.18.30")
	
    testCompileOnly("org.projectlombok:lombok:1.18.30") 
	testAnnotationProcessor("org.projectlombok:lombok:1.18.30")

    compileOnly("com.comphenix.protocol:ProtocolLib:5.1.0")
}

tasks {
    named<Jar>("jar") {
        finalizedBy("shadowJar")
        manifest {
            attributes(mapOf("Main-Class" to "net.kamilereon.lylac_system.LylacSystem"))
        }
        //destinationDirectory = file("C:\\Users\\windopper\\Desktop\\mc-server\\dev\\plugins")
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}
