/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.kamilereon.lylac_system;

import org.junit.Test;

public class AppTest {
    @Test
    public void appHasAGreeting() {

    }
}
